<?php $userModel = new Application_Model_Users()?>
<div class="profile_picture">
    <?php echo $this->image('name', $userModel->getImageUrl($this->data['image']), array('alt' => 'image alt'), 'small'); ?>   
</div>
<div class="left_profile_links">
    <ul>
        <li>
            <a title="" href="<?php $this->baseUrl()?>/user/manage">Manage Profile</a>
        </li>
        <li>
            <a title="" href="#">View Results</a>
        </li>
        <li>
            <a title="" href="#">View Training</a>
        </li>
        <li>
            <a title="" href="#">View Coach(es)</a>
        </li>
    </ul>
</div>
<div class="left_friends_ttl">
<?php echo phpinfo()?>    
</div>
