<?php $userModel = new Application_Model_Users()?>
<div class="left_main_container">
    <div class="profile_name_description">
        <h4><?php print_r($userModel->getCurrentUserName())?></h4>
    </div>
    <div class="profile_picture">
        <?php echo $this->image('name', $userModel->getImageUrl($this->data['image']), array('alt' => 'image alt'), 'small'); ?>
        <?php //die($userModel->getImageUrl($this->data['image']));?>
    </div>
</div>
<div class="center_main_container">

</div>